import React from "react";
import Sticky from "react-stickynode";
import Header from "../header";
import Head from "next/head";
import Footer from "../footer";

function Layout({ children }) {
  const [isSticky, setIsSticky] = React.useState(false);
  const handleStateChange = (status) => {
    if (status.status === Sticky.STATUS_FIXED) {
      setIsSticky(true);
    } else if (status.status === Sticky.STATUS_ORIGINAL) {
      setIsSticky(false);
    }
  };
  return (
    <React.Fragment>
      <Head>
        <title>The Halftimers</title>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Sticky innerZ={1001} top={0} onStateChange={handleStateChange}> */}
        <Header className={`${isSticky ? "sticky" : "unSticky"}`} />
        <main id="page_container">{children}</main>
        <Footer />
      {/* </Sticky> */}
    </React.Fragment>
  );
}

export default Layout;
